AllCops:
   Exclude:
    - db/**/*
    - bin/**/*
    - '**/config/**/*'

   TargetRubyVersion: 2.3.1

Rails:
  Enabled: true
Metrics/MethodLength:
  Max: 120
Metrics/AbcSize:
  Max: 35
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/EmptyMethod:
  Enabled: false